'use strict';

/*
 * MEHEK product catalogue.
 * This single array is used by the Shop page and the dynamic Product page.
 */
window.products = [
  {
    id: 1,
    slug: 'oud-legacy',
    name: 'Oud Legacy',
    collection: 'heritage',
    category: 'perfume',
    type: 'Eau de Parfum',
    gender: 'unisex',
    price: 145,
    images: ['media/images/products/oud-legacy.png', 'media/images/products/oud-legacy1.png'],
    description: 'A deep and enveloping fragrance where precious oud meets saffron, warm amber and polished woods.',
    notes: { top: 'Saffron, bergamot', heart: 'Rose, incense', base: 'Oud, amber, sandalwood' },
    variants: [{ label: '50 ml', price: 145 }]
  },
  {
    id: 2,
    slug: 'velvet-rose',
    name: 'Velvet Rose',
    collection: 'heritage',
    category: 'perfume',
    type: 'Eau de Parfum',
    gender: 'women',
    price: 140,
    images: ['media/images/products/velvet-rose.webp'],
    description: 'A soft yet expressive rose fragrance layered with pink pepper, amber and a smooth veil of musk.',
    notes: { top: 'Pink pepper, bergamot', heart: 'Damask rose, jasmine', base: 'Amber, musk, cedarwood' },
    variants: [{ label: '50 ml', price: 140 }]
  },
  {
    id: 3,
    slug: 'milano-noir',
    name: 'Milano Noir',
    collection: 'milano',
    category: 'perfume',
    type: 'Eau de Parfum',
    gender: 'men',
    price: 135,
    images: ['media/images/products/milano-noir.png', 'media/images/products/milano-noir.webp'],
    description: 'A refined evening scent combining aromatic citrus, iris and dark woods with a modern Italian character.',
    notes: { top: 'Bergamot, black pepper', heart: 'Iris, lavender', base: 'Vetiver, cedarwood, musk' },
    variants: [{ label: '50 ml', price: 135 }]
  },
  {
    id: 4,
    slug: 'london-bloom',
    name: 'London Bloom',
    collection: 'london',
    category: 'perfume',
    type: 'Eau de Parfum',
    gender: 'women',
    price: 150,
    images: ['media/images/products/london-bloom.png', 'media/images/products/london-bloom.webp'],
    description: 'A luminous floral fragrance inspired by London gardens after rain, with airy petals and clean woods.',
    notes: { top: 'Pear, bergamot', heart: 'Peony, jasmine', base: 'White musk, cedarwood' },
    variants: [{ label: '50 ml', price: 150 }]
  },
  {
    id: 5,
    slug: 'black-tobacco',
    name: 'Black Tobacco',
    collection: 'heritage',
    category: 'perfume',
    type: 'Eau de Parfum',
    gender: 'men',
    price: 148,
    images: ['media/images/products/black-tabacco.png'],
    description: 'A rich composition of tobacco leaf, warm spice and smoky woods with a smooth amber finish.',
    notes: { top: 'Cardamom, cinnamon', heart: 'Tobacco leaf, leather', base: 'Amber, patchouli, oud' },
    variants: [{ label: '50 ml', price: 148 }]
  },
  {
    id: 6,
    slug: 'italian-bergamot',
    name: 'Italian Bergamot',
    collection: 'milano',
    category: 'perfume',
    type: 'Eau de Parfum',
    gender: 'unisex',
    price: 132,
    images: ['media/images/products/italian-bergamot.png'],
    description: 'A bright and elegant citrus fragrance softened by neroli, white tea and clean musk.',
    notes: { top: 'Italian bergamot, lemon', heart: 'Neroli, white tea', base: 'Musk, sandalwood' },
    variants: [{ label: '50 ml', price: 132 }]
  },
  {
    id: 7,
    slug: 'velvet-peony',
    name: 'Velvet Peony',
    collection: 'milano',
    category: 'perfume',
    type: 'Eau de Parfum',
    gender: 'women',
    price: 138,
    images: ['media/images/products/milano-noir.webp'],
    description: 'A polished floral blend of peony, iris and jasmine resting on creamy sandalwood and white musk.',
    notes: { top: 'Mandarin, pear', heart: 'Peony, iris, jasmine', base: 'White musk, sandalwood' },
    variants: [{ label: '50 ml', price: 138 }]
  },
  {
    id: 8,
    slug: 'cashmere-woods',
    name: 'Cashmere Woods',
    collection: 'london',
    category: 'perfume',
    type: 'Eau de Parfum',
    gender: 'unisex',
    price: 145,
    images: ['media/images/products/cashmeer-wood.png'],
    description: 'A soft woody fragrance with fig, cashmere accords and warm cedar, designed for quiet everyday luxury.',
    notes: { top: 'Fig leaf, bergamot', heart: 'Cashmere wood, violet', base: 'Cedarwood, musk, amber' },
    variants: [{ label: '50 ml', price: 145 }]
  },
  {
    id: 9,
    slug: 'midnight-london',
    name: 'Midnight London',
    collection: 'london',
    category: 'perfume',
    type: 'Eau de Parfum',
    gender: 'men',
    price: 152,
    images: ['media/images/products/midnight.png'],
    description: 'A dark urban fragrance blending black tea, aromatic spice and vetiver over a smooth woody base.',
    notes: { top: 'Black pepper, bergamot', heart: 'Black tea, lavender', base: 'Vetiver, patchouli, cedarwood' },
    variants: [{ label: '50 ml', price: 152 }]
  },
  {
    id: 10,
    slug: 'heritage-hair-mist',
    name: 'Heritage Hair Mist',
    collection: 'heritage',
    category: 'hair-mist',
    type: 'Hair Mist',
    gender: 'unisex',
    price: 55,
    images: ['media/images/products/heritage-hair-mist.png', 'media/images/products/fd7e1d2f-03b3-4899-a661-b67a4551a881.png'],
    description: 'A lightweight scented mist that leaves the hair softly fragranced with rose, amber and cedarwood.',
    notes: { top: 'Bergamot, freesia, pink pepper', heart: 'Damask rose, jasmine, lavender', base: 'Amber, cedarwood, musk' },
    variants: [{ label: '100 ml', price: 55 }]
  },
  {
    id: 11,
    slug: 'milano-hair-mist',
    name: 'Milano Hair Mist',
    collection: 'milano',
    category: 'hair-mist',
    type: 'Hair Mist',
    gender: 'unisex',
    price: 55,
    images: ['media/images/products/milano-hair-mist.png', 'media/images/products/milano-hair-mist1.png'],
    description: 'A fresh hair mist with bergamot, iris and white musk for a clean and refined scented finish.',
    notes: { top: 'Bergamot, mandarin', heart: 'Iris, jasmine', base: 'White musk, sandalwood' },
    variants: [{ label: '100 ml', price: 55 }]
  },
  {
    id: 12,
    slug: 'london-hair-mist',
    name: 'London Hair Mist',
    collection: 'london',
    category: 'hair-mist',
    type: 'Hair Mist',
    gender: 'unisex',
    price: 55,
    images: ['media/images/products/london-hair-mist.png', 'media/images/products/london-hair-mist1.png'],
    description: 'A contemporary hair mist combining airy florals, black tea and clean woods.',
    notes: { top: 'Pear, bergamot', heart: 'Black tea, violet', base: 'Cedarwood, musk' },
    variants: [{ label: '100 ml', price: 55 }]
  },
  {
    id: 13,
    slug: 'heritage-candle',
    name: 'Heritage Candle',
    collection: 'heritage',
    category: 'scented-candle',
    type: 'Scented Candle',
    gender: '',
    price: 48,
    images: ['media/images/products/heritage- candela.png'],
    description: 'A warm home fragrance built around amber, rose, spice and dark woods.',
    notes: { top: 'Saffron, spice', heart: 'Rose, incense', base: 'Amber, oud, cedarwood' },
    variants: [{ label: '200 g', price: 48 }, { label: '500 g', price: 78 }]
  },
  {
    id: 14,
    slug: 'milano-candle',
    name: 'Milano Candle',
    collection: 'milano',
    category: 'scented-candle',
    type: 'Scented Candle',
    gender: '',
    price: 48,
    images: ['media/images/products/milano-candle.png'],
    description: 'A luminous candle with bergamot, iris and creamy sandalwood.',
    notes: { top: 'Bergamot, lemon', heart: 'Iris, jasmine', base: 'Sandalwood, white musk' },
    variants: [{ label: '200 g', price: 48 }, { label: '500 g', price: 78 }]
  },
  {
    id: 15,
    slug: 'london-candle',
    name: 'London Candle',
    collection: 'london',
    category: 'scented-candle',
    type: 'Scented Candle',
    gender: '',
    price: 48,
    images: ['media/images/products/london-candle.png'],
    description: 'A modern candle blending black tea, fig and refined woods.',
    notes: { top: 'Bergamot, fig', heart: 'Black tea, violet', base: 'Cedarwood, vetiver' },
    variants: [{ label: '200 g', price: 48 }, { label: '500 g', price: 78 }]
  },
  {
    id: 16,
    slug: 'heritage-diffuser',
    name: 'Heritage Reed Diffuser',
    collection: 'heritage',
    category: 'reed-diffuser',
    type: 'Reed Diffuser',
    gender: '',
    price: 58,
    images: ['media/images/products/heritage-diffuser.png'],
    description: 'A long-lasting diffuser that fills the room with warm amber, rose and oud.',
    notes: { top: 'Saffron, spice', heart: 'Rose, incense', base: 'Amber, oud, cedarwood' },
    variants: [{ label: '200 ml', price: 58 }, { label: '500 ml', price: 92 }]
  },
  {
    id: 17,
    slug: 'milano-diffuser',
    name: 'Milano Reed Diffuser',
    collection: 'milano',
    category: 'reed-diffuser',
    type: 'Reed Diffuser',
    gender: '',
    price: 58,
    images: ['media/images/products/milano-diffuser.png'],
    description: 'A bright diffuser with citrus, iris and soft white musk.',
    notes: { top: 'Bergamot, lemon', heart: 'Iris, jasmine', base: 'Sandalwood, white musk' },
    variants: [{ label: '200 ml', price: 58 }, { label: '500 ml', price: 92 }]
  },
  {
    id: 18,
    slug: 'london-diffuser',
    name: 'London Reed Diffuser',
    collection: 'london',
    category: 'reed-diffuser',
    type: 'Reed Diffuser',
    gender: '',
    price: 58,
    images: ['media/images/products/london-diffuser.png'],
    description: 'A contemporary diffuser scented with black tea, fig and clean woods.',
    notes: { top: 'Bergamot, fig', heart: 'Black tea, violet', base: 'Cedarwood, vetiver' },
    variants: [{ label: '200 ml', price: 58 }, { label: '500 ml', price: 92 }]
  },
  {
    id: 19,
    slug: 'heritage-room-spray',
    name: 'Heritage Room Spray',
    collection: 'heritage',
    category: 'room-spray',
    type: 'Room Spray',
    gender: '',
    price: 42,
    images: ['media/images/products/heritage room-spray.png'],
    description: 'An immediate veil of rose, spice, amber and oud for the home.',
    notes: { top: 'Saffron, spice', heart: 'Rose, incense', base: 'Amber, oud' },
    variants: [{ label: '150 ml', price: 42 }]
  },
  {
    id: 20,
    slug: 'milano-room-spray',
    name: 'Milano Room Spray',
    collection: 'milano',
    category: 'room-spray',
    type: 'Room Spray',
    gender: '',
    price: 42,
    images: ['media/images/products/milano-room-spray.png'],
    description: 'A crisp room spray with bergamot, iris and white musk.',
    notes: { top: 'Bergamot, lemon', heart: 'Iris, jasmine', base: 'White musk' },
    variants: [{ label: '150 ml', price: 42 }]
  },
  {
    id: 21,
    slug: 'london-room-spray',
    name: 'London Room Spray',
    collection: 'london',
    category: 'room-spray',
    type: 'Room Spray',
    gender: '',
    price: 42,
    images: ['media/images/products/london-roomspray.png'],
    description: 'A modern room spray combining black tea, fig and cedarwood.',
    notes: { top: 'Bergamot, fig', heart: 'Black tea, violet', base: 'Cedarwood, vetiver' },
    variants: [{ label: '150 ml', price: 42 }]
  }
];
